export const COLORS = {
  PRIMARY: '#0B3DA9',
  SECONDARY: '#FFFFFF',
  TERTIARY: '#FFFFFF',
  QUATERNARY: '#E0E0E0',
  PENTAGONAL: '#F0F0F0',
  HEXAGONAL: '#F5F5F5',
  SEPTAGONAL: '#FAFAFA',
  OCTAGONAL: '#FFFFFF',
};
